language: python

python:
  # originally I built with Python 3.4, but it turned out the travis-ci
  # clang build slaves only offer Python 3.2, so let's make this the
  # minimum requirement instead:
  - 3.2

before_install:
  # we need to install gyp before running tests, otherwise the 'bru make'
  # tests will fail
  - sudo apt-get update -qq
  - sudo apt-get install -y gyp

install:
  - pip install -r requirements-dev.txt --use-mirrors

script:
  - nosetests --with-coverage --cover-package=brulib

after_success:
  - coveralls