language: python

python:
  - 3.4

before_install:
  # we need to install gyp before running tests, otherwise the 'bru make'
  # tests will fail
  - sudo apt-get update -qq
  - sudo apt-get install -y gyp

install:
  - pip install -r requirements-dev.txt --use-mirrors

script:
  - nosetests --with-coverage --cover-package=brulib

after_success:
  - coveralls